version: "3"

services:
    # Servicio para PostgreSQL
    postgres-prod:
        image: postgres:latest
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: db_test
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    # Servicio para la aplicación FastAPI
    fastapi-prod:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - postgres-prod
        environment:
            DB_NAME: db_test
            DB_USER: myuser
            DB_PASSWORD: mypassword
            DB_PORT: 5432
            DB_HOST: postgres-prod
            DATABASE_URL: postgresql://myuser:mypassword@postgres-prod:5432/mydatabase

volumes:
    pgdata:
